[package]
name = "ultra-nlp"
version = "0.2.0"
edition = "2021"
license = "MIT"
description = "A NLP library."
repository = "https://github.com/BlackGlory/ultra-nlp"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
daachorse = "0.4.3"
